apiVersion: v1
data:
  01-default-users.ldif: |-
    # Units
    dn: ou=Users,dc=cp
    objectClass: organizationalUnit
    ou: Users

    dn: ou=Groups,dc=cp
    objectClass: organizationalUnit
    ou: Groups

    # Groups
    dn: cn=cpadmins,ou=Groups,dc=cp
    objectClass: groupOfNames
    objectClass: top
    cn: cpadmins
    member: cn=cpadmin,ou=Users,dc=cp
    member: cn=cpadmin1,ou=Users,dc=cp
    member: cn=cpadmin2,ou=Users,dc=cp

    dn: cn=cpusers,ou=Groups,dc=cp
    objectClass: groupOfNames
    objectClass: top
    cn: cpusers
    member: cn=cpadmin,ou=Users,dc=cp
    member: cn=cpadmin1,ou=Users,dc=cp
    member: cn=cpadmin2,ou=Users,dc=cp
    member: cn=cpuser,ou=Users,dc=cp
    member: cn=cpuser1,ou=Users,dc=cp
    member: cn=cpuser2,ou=Users,dc=cp

    dn: cn=cpusers1,ou=Groups,dc=cp
    objectClass: groupOfNames
    objectClass: top
    cn: cpusers1
    member: cn=cpuser,ou=Users,dc=cp
    member: cn=cpuser1,ou=Users,dc=cp
    member: cn=cpuser2,ou=Users,dc=cp

    # Users
    dn: cn=cpadmin,ou=Users,dc=cp
    objectClass: inetOrgPerson
    objectClass: top
    cn: cpadmin
    sn: cpadmin
    uid: cpadmin
    mail: cpadmin@cp.local
    userpassword: REPLACEME
    employeeType: admin

    dn: cn=cpadmin1,ou=Users,dc=cp
    objectClass: inetOrgPerson
    objectClass: top
    cn: cpadmin1
    sn: cpadmin1
    uid: cpadmin1
    mail: cpadmin1@cp.local
    userpassword: REPLACEME
    employeeType: admin

    dn: cn=cpadmin2,ou=Users,dc=cp
    objectClass: inetOrgPerson
    objectClass: top
    cn: cpadmin2
    sn: cpadmin2
    uid: cpadmin2
    mail: cpadmin2@cp.local
    userpassword: REPLACEME
    employeeType: admin

    dn: cn=cpuser,ou=Users,dc=cp
    objectClass: inetOrgPerson
    objectClass: top
    cn: cpuser
    sn: cpuser
    uid: cpuser
    mail: cpuser@cp.local
    userpassword: REPLACEME

    dn: cn=cpuser1,ou=Users,dc=cp
    objectClass: inetOrgPerson
    objectClass: top
    cn: cpuser1
    sn: cpuser1
    uid: cpuser1
    mail: cpuser1@cp.local
    userpassword: REPLACEME

    dn: cn=cpuser2,ou=Users,dc=cp
    objectClass: inetOrgPerson
    objectClass: top
    cn: cpuser2
    sn: cpuser2
    uid: cpuser2
    mail: cpuser2@cp.local
    userpassword: REPLACEME
kind: ConfigMap
metadata:
  labels:
    app: openldap
  name: openldap-customldif
